apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: rgw-ps-channel
  namespace: rgwpubsub
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory-channel
